# type: ignore
"""Added indexes on FKs and fields that are filtered or joined

Revision ID: 5d254799dbb3
Revises: 7638bdce9997
Create Date: 2026-05-16 17:20:01.275852

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "5d254799dbb3"
down_revision: Union[str, Sequence[str], None] = "7638bdce9997"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("pix_comment_author_id"), "comment", ["author_id"], unique=False
    )
    op.create_index(op.f("ix_comment_task_id"), "comment", ["task_id"], unique=False)
    op.create_index(op.f("ix_project_owner_id"), "project", ["owner_id"], unique=False)
    op.create_index(op.f("ix_task_project_id"), "task", ["project_id"], unique=False)
    op.create_index(op.f("ix_task_status"), "task", ["status"], unique=False)
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_index(op.f("ix_task_status"), table_name="task")
    op.drop_index(op.f("ix_task_project_id"), table_name="task")
    op.drop_index(op.f("ix_project_owner_id"), table_name="project")
    op.drop_index(op.f("ix_comment_task_id"), table_name="comment")
    op.drop_index(op.f("ix_comment_author_id"), table_name="comment")
    # ### end Alembic commands ###
