"""Added orphan deletion when parent tables are deleted

Revision ID: 7638bdce9997
Revises: 6f7bf90a038a
Create Date: 2026-05-16 16:19:57.040248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7638bdce9997'
down_revision: Union[str, Sequence[str], None] = '6f7bf90a038a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('comment_task_id_fkey'), 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'task', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('task_project_id_fkey'), 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key(op.f('task_project_id_fkey'), 'task', 'project', ['project_id'], ['id'])
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key(op.f('comment_task_id_fkey'), 'comment', 'task', ['task_id'], ['id'])
    # ### end Alembic commands ###
